import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { Bar, BarChart, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../api/client'
import type { AskResponse, Profile, Recommendation, RecommendationResult } from '../api/types'

const gradeLadder = ['Junior', 'Middle', 'Senior', 'Lead']
const formatName = (value: string) => value.replace('_', ' ')
const skillName = (id: string, profile: Profile) => profile.skills.find((s) => s.skill_id === id)?.name || id.replace('SK_', '').replace(/_/g, ' ')
function Pill({ children, tone = 'green' }: { children: React.ReactNode; tone?: 'green' | 'amber' | 'slate' }) { return <span className={`pill pill-${tone}`}>{children}</span> }
function Readiness({ value }: { value: number }) { return <div className="readiness"><svg viewBox="0 0 36 36"><path className="ring-bg" d="M18 2.5a15.5 15.5 0 1 1 0 31a15.5 15.5 0 1 1 0-31"/><path className="ring" strokeDasharray={`${value}, 100`} d="M18 2.5a15.5 15.5 0 1 1 0 31a15.5 15.5 0 1 1 0-31"/></svg><b>{value}%</b></div> }
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`card ${className}`}>{children}</section> }

function Trajectory({ profile, result }: { profile: Profile; result: RecommendationResult }) { const current = profile.employee.grade; const target = profile.target.grade; return <Card><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow">TRAJECTORY</p><h2 className="section-title">Your path to {target || 'your next step'}</h2></div><div className="flex items-center gap-3"><Readiness value={profile.readiness.pct} /><span className="text-sm text-slate-500">readiness today</span></div></div><div className="ladder">{gradeLadder.map((grade, index) => <div key={grade} className="ladder-step"><div className={`ladder-dot ${grade === current ? 'is-current' : grade === target ? 'is-target' : ''}`}>{grade === current ? '●' : index + 1}</div><b>{grade}</b><small>{grade === current ? 'Current' : grade === target ? 'Target' : ''}</small></div>)}</div><div className="mt-8 grid gap-4 border-t border-line pt-6 sm:grid-cols-2"><div><p className="muted-label">CRITICAL SKILLS</p><p className="mt-1 text-xl font-semibold text-ink">{profile.readiness.critical_met} of {profile.readiness.critical_total} met</p></div><div><p className="muted-label">PROJECTED READINESS</p><div className="mt-2 flex gap-2">{result.trajectory.after_pct.map((score, index) => <span key={score} className="projection">After {index + 1}: <b>{score}%</b></span>)}</div></div></div></Card> }
function SkillsChart({ profile }: { profile: Profile }) { const data = profile.skills.map((s) => ({ ...s, label: s.name.length > 16 ? `${s.name.slice(0, 15)}…` : s.name })); return <Card><div className="flex items-start justify-between"><div><p className="eyebrow">SKILLS AGAINST TARGET</p><h2 className="section-title">Your strongest next moves</h2></div><span className="text-xs text-slate-500">Effective / Senior target</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={260}><BarChart data={data} layout="vertical" margin={{ top: 10, right: 12, left: 8, bottom: 0 }} barGap={5}><XAxis type="number" domain={[0, 5]} tickCount={6} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="label" width={112} axisLine={false} tickLine={false} /><Tooltip cursor={{ fill: '#f3f7f5' }} formatter={(v, n) => [v, n === 'effective' ? 'Effective' : 'Target']} /><Bar dataKey="effective" name="effective" radius={[4, 4, 4, 4]} isAnimationActive animationDuration={700}>{data.map((x) => <Cell key={x.skill_id} fill={x.critical ? '#1f6b57' : '#95b9aa'} />)}</Bar><Bar dataKey="required_target" name="required_target" fill="#dce8e2" radius={[4, 4, 4, 4]} isAnimationActive animationDuration={700} /></BarChart></ResponsiveContainer></div><div className="mt-3 flex flex-wrap gap-2">{profile.skills.filter((s) => s.pending_from.length).map((s) => <Pill key={s.skill_id} tone="amber">Pending review · {s.name} ({s.pending_from.join(', ')})</Pill>)}</div></Card> }
function RecommendationCard({ item, profile, ai, onAction, busy }: { item: Recommendation; profile: Profile; ai: boolean; onAction: (action: 'complete' | 'enroll' | 'not_now') => void; busy: boolean }) { const [expanded, setExpanded] = useState(false); return <Card className="recommendation"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex gap-2"><Pill>STEP {item.rank}</Pill>{ai && <Pill tone="slate">✦ AI</Pill>}</div><h3 className="mt-3 text-xl font-semibold text-ink">{item.title}</h3><p className="mt-1 text-sm capitalize text-slate-500">{item.type} · {formatName(item.format)} · {item.duration_hours} hours{item.next_session ? ` · ${new Date(item.next_session).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}` : ''}</p></div><div className="score"><span>Score</span><b>{item.score.toFixed(2)}</b></div></div><p className="mt-5 leading-7 text-slate-700">{item.rationale}</p><div className="mt-5 flex flex-wrap gap-2">{item.factors.slice(0, 4).map((f) => <Pill key={f.kind} tone={f.kind === 'critical_gap' ? 'amber' : 'green'}>{f.label}</Pill>)}</div><div className="gain-row">{item.expected_gains.map((gain) => <span key={gain.skill_id}>Expected gain <b>{skillName(gain.skill_id, profile)} {gain.from} → {gain.to}</b></span>)}<span>Readiness after <b>{item.readiness_after_pct}%</b></span></div><button className="calculation-toggle" onClick={() => setExpanded(!expanded)}>How this was calculated <span>{expanded ? '−' : '+'}</span></button>{expanded && <div className="calculation">{item.factors.map((factor) => <div key={factor.kind}><span>{factor.label}</span><b>{factor.impact.toFixed(2)}</b></div>)}<div className="font-semibold"><span>Final recommendation score</span><b>{item.score.toFixed(2)}</b></div></div>}<div className="mt-6 flex flex-wrap gap-3"><button disabled={busy} className="primary-button" onClick={() => onAction('enroll')}>Join</button><button disabled={busy} className="secondary-button" onClick={() => onAction('not_now')}>Not now</button><button disabled={busy} className="text-button" onClick={() => onAction('complete')}>Mark completed</button></div></Card> }
function History({ profile }: { profile: Profile }) { return <Card><p className="eyebrow">ACTIVITY HISTORY</p><h2 className="section-title">Learning activity</h2><div className="timeline">{profile.history.map((event) => <div key={event.record_id || event.event_id} className="timeline-row"><span className={`status-dot status-${event.status}`}/><div><b>{event.title}</b><p>{event.date ? new Date(event.date).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' }) : 'No date'} · <span className="capitalize">{event.status.replace('_', ' ')}</span></p></div>{event.feedback_rating && <Pill tone="slate">★ {event.feedback_rating}</Pill>}</div>)}</div></Card> }
function ProgressBadge({ profile }: { profile: Profile }) {
  const voluntary = profile.history.filter((h) => h.status === 'completed' && h.assigned_by === 'self').length
  const xp = voluntary * 100 + profile.readiness.critical_met * 250
  const level = 1 + Math.floor(xp / 500)
  return <div className="xp" title="Points for voluntary growth — private, never a leaderboard"><span>LEVEL {level}</span><b>{xp} XP</b><small>{voluntary} voluntary · {profile.readiness.critical_met}/{profile.readiness.critical_total} critical</small></div>
}

function AskBox({ id, lang }: { id: string; lang: string }) {
  const [q, setQ] = useState(''); const [answer, setAnswer] = useState<AskResponse | null>(null); const [loading, setLoading] = useState(false)
  const suggestions = ['Why this step and not my weakest skill?', 'How close am I to my target grade?', 'What will this activity give me?']
  async function ask(question: string) { const text = question.trim(); if (!text) return; setQ(text); setLoading(true); setAnswer(null); try { setAnswer(await api.ask(id, text, lang)) } catch { setAnswer({ answer: 'Sorry, I could not answer that right now.', generated_by: 'rules', model: null, latency_ms: 0 }) } finally { setLoading(false) } }
  return <Card className="ask-box"><p className="eyebrow">ASK ABOUT YOUR PATH</p><h2 className="section-title">Questions, answered from your own data</h2><div className="mt-3 flex gap-2"><input className="input" value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') ask(q) }} placeholder="e.g. Why not my weakest skill?" /><button className="primary-button shrink-0" disabled={loading} onClick={() => ask(q)}>{loading ? '…' : 'Ask'}</button></div><div className="mt-3 flex flex-wrap gap-2">{suggestions.map((sug) => <button key={sug} className="chip" disabled={loading} onClick={() => ask(sug)}>{sug}</button>)}</div>{answer && <div className="ask-answer"><p>{answer.answer}</p><p className="ask-source">{answer.generated_by === 'llm' ? '✦ AI · grounded in your plan' : 'From your plan'}</p></div>}</Card>
}

export function EmployeePage({ onSignOut }: { onSignOut: () => void }) { const { id = '' } = useParams(); const [profile, setProfile] = useState<Profile | null>(null); const [rules, setRules] = useState<RecommendationResult | null>(null); const [result, setResult] = useState<RecommendationResult | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [completed, setCompleted] = useState<{ before: number; after: number; gains: { skill_id: string; from: number; to: number }[] } | null>(null); const [lang, setLang] = useState('')
  const load = async () => { setError(''); try { const [nextProfile, nextRules] = await Promise.all([api.profile(id), api.recommendations(id, 'rules')]); setProfile(nextProfile); setRules(nextRules); setResult(nextRules); setLang(nextProfile.employee.preferred_language); api.recommendations(id, 'ai', nextProfile.employee.preferred_language).then(setResult).catch(() => undefined) } catch (e) { setError(e instanceof Error ? e.message : 'Could not load your path.') } }
  useEffect(() => { void load() }, [id])
  async function action(eventId: string, actionType: 'complete' | 'enroll' | 'not_now') { setBusy(true); try { const update = await api.action(id, eventId, actionType); if (actionType === 'complete') { setCompleted({ before: update.readiness_before, after: update.readiness_after, gains: update.skills_changed }); await load() } } catch (e) { setError(e instanceof Error ? e.message : 'Action could not be saved.') } finally { setBusy(false) } }
  async function switchLang(next: string) { if (next === lang) return; setLang(next); if (rules) setResult(rules); try { const ai = await api.recommendations(id, 'ai', next); setResult(ai) } catch { /* keep rules */ } }
  if (error && !profile) return <main className="center-message"><p>{error}</p><button className="primary-button" onClick={load}>Try again</button></main>
  if (!profile || !rules || !result) return <main className="loading"><div className="loader"/><p>Preparing your path…</p></main>
  return <main className="min-h-screen bg-mist"><header className="topbar"><div className="brand"><span>↗</span> CAREER QUEST</div><div className="flex items-center gap-4"><span className="hidden text-sm text-slate-500 sm:block">My path</span><button className="signout" onClick={onSignOut}>Sign out</button></div></header><div className="mx-auto max-w-6xl px-5 py-9 md:px-8"><header className="profile-header"><div className="avatar large">{profile.employee.full_name.split(' ').map((x) => x[0]).join('')}</div><div><p className="eyebrow">MY PATH</p><h1>{profile.employee.full_name}</h1><p>{profile.employee.role} · {profile.employee.grade} · {profile.employee.tenure_months} months at Halyk Bank</p></div><ProgressBadge profile={profile} /><div className="goal"><span>GOAL</span><b>{profile.target.grade ? `${profile.target.role} · ${profile.target.grade}` : 'Explore my options'}</b></div></header>{error && <p className="notice">{error}</p>}{completed && <section className="completion"><div><Pill>COMPLETED</Pill><h2>Nice work — your path has moved forward.</h2><p>{completed.gains.map((g) => `${skillName(g.skill_id, profile)} ${g.from} → ${g.to}`).join(', ')}</p></div><div className="completion-score"><s>{completed.before}%</s><b>{completed.after}%</b><span>readiness</span></div><button onClick={() => setCompleted(null)}>×</button></section>}<div className="page-grid"><div className="space-y-6"><Trajectory profile={profile} result={result}/><SkillsChart profile={profile}/><History profile={profile}/></div><aside className="space-y-6"><div className="recommendation-heading"><div><p className="eyebrow">NEXT STEPS</p><h2 className="section-title">Thoughtful options for you</h2></div><div className="flex items-center gap-3">{result.generated_by === 'rules' && <span className="text-xs text-slate-400">Refining the explanation…</span>}<div className="lang-switch">{([['kk','ҚАЗ'],['ru','РУС'],['en','ENG']] as const).map(([code,label]) => <button key={code} className={`lang-chip ${lang === code ? 'lang-chip-active' : ''}`} onClick={() => switchLang(code)}>{label}</button>)}</div></div></div>{result.recommendations.map((item) => <RecommendationCard key={item.event_id} item={item} profile={profile} ai={result.generated_by === 'llm'} busy={busy} onAction={(actionType) => action(item.event_id, actionType)} />)}{result.not_recommended.map((note, i) => <div key={i} className="why-not"><b>Why not {note.skill_id ? skillName(note.skill_id, profile) : 'this option'}?</b><p>{note.reason}</p></div>)}<AskBox id={id} lang={lang || profile.employee.preferred_language} />{profile.assigned.length > 0 && <Card><p className="eyebrow">ASSIGNED BY HR</p><h2 className="section-title">Separate from your choices</h2>{profile.assigned.map((a) => <div key={a.event_id} className="assigned"><div><b>{a.title}</b><p>Due {a.due_date ? new Date(a.due_date).toLocaleDateString() : '—'}</p></div><Pill tone="amber">{a.status}</Pill></div>)}</Card>}</aside></div></div></main> }
