import { useEffect, useState } from 'react'
import { Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { api, auth } from './api/client'
import type { AuthSession, DemoPerson } from './api/types'
import { EmployeePage } from './pages/EmployeePage'

function Login({ onLogin }: { onLogin: (session: AuthSession) => void }) {
  const navigate = useNavigate(); const [role, setRole] = useState<'employee' | 'hr'>('employee'); const [people, setPeople] = useState<DemoPerson[]>([]); const [query, setQuery] = useState(''); const [person, setPerson] = useState<DemoPerson | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  useEffect(() => { api.people().then(setPeople).catch(() => setError('Could not load the people directory.')) }, [])
  const filtered = people.filter((p) => `${p.full_name} ${p.role} ${p.employee_id}`.toLowerCase().includes(query.toLowerCase()))
  async function enter() { setError(''); if (role === 'employee' && !person) return setError('Choose an employee profile to continue.'); setLoading(true); try { const next = await api.login(role, person?.employee_id); auth.set(next); onLogin(next); navigate(role === 'hr' ? '/hr' : `/me/${next.employee_id}`) } catch (e) { setError(e instanceof Error ? e.message : 'Sign in failed.') } finally { setLoading(false) } }
  return <main className="min-h-screen bg-mist px-5 py-10"><section className="mx-auto grid max-w-5xl overflow-hidden rounded-3xl bg-white shadow-card md:grid-cols-[.9fr_1.1fr]"><div className="bg-ink p-8 text-white md:p-12"><div className="flex items-center gap-3 text-sm font-semibold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#b9e5b4] text-ink">↗</span> CAREER QUEST</div><div className="mt-20"><p className="text-[#b9e5b4]">Halyk Bank · growth, in context</p><h1 className="mt-4 text-4xl font-semibold leading-tight">A clearer path to your next role.</h1><p className="mt-5 max-w-sm text-white/70">Explore skills, thoughtful recommendations, and the progress that matters to you.</p></div></div><div className="p-8 md:p-12"><p className="text-sm font-medium text-pine">WELCOME</p><h2 className="mt-2 text-2xl font-semibold text-ink">Choose your workspace</h2><div className="mt-7 grid grid-cols-2 rounded-xl bg-mist p-1"><button className={`tab ${role === 'employee' ? 'tab-active' : ''}`} onClick={() => setRole('employee')}>Employee</button><button className={`tab ${role === 'hr' ? 'tab-active' : ''}`} onClick={() => setRole('hr')}>HR partner</button></div>{role === 'employee' ? <div className="mt-7"><label className="label">Find your profile</label><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by name or role" className="input" />{query && <div className="picker">{filtered.map((p) => <button key={p.employee_id} onClick={() => { setPerson(p); setQuery('') }} className="picker-row"><span className="avatar">{p.full_name.split(' ').map((x) => x[0]).join('')}</span><span><b>{p.full_name}</b><small>{p.role} · {p.grade}</small></span></button>)}</div>}{person ? <button className="selected-person" onClick={() => setPerson(null)}><span className="avatar">{person.full_name.split(' ').map((x) => x[0]).join('')}</span><span><b>{person.full_name}</b><small>{person.role} · {person.grade}</small></span><span>×</span></button> : <p className="mt-3 text-sm text-slate-500">Search and select a profile.</p>}</div> : <p className="mt-8 rounded-xl bg-sand p-4 text-sm leading-6 text-slate-600">You’ll see organization-level development signals. Individual employee recommendations remain private.</p>}{error && <p className="mt-5 text-sm text-red-600">{error}</p>}<button disabled={loading} onClick={enter} className="primary-button mt-8 w-full">{loading ? 'Opening workspace…' : 'Continue'} <span>→</span></button><p className="mt-5 text-center text-xs text-slate-400">Demo access · no password required</p></div></section></main>
}
function HrPlaceholder() { return <main className="min-h-screen bg-mist p-8"><section className="mx-auto max-w-3xl rounded-3xl bg-white p-12 shadow-card"><p className="text-sm font-medium text-pine">HR WORKSPACE</p><h1 className="mt-2 text-3xl font-semibold text-ink">HR view is on its way</h1><p className="mt-4 text-slate-600">The platform team is connecting the organization overview. This frontend already supports HR sign-in.</p><button onClick={() => { auth.set(null); location.href = '/' }} className="secondary-button mt-8">Sign out</button></section></main> }
export default function App() { const [session, setSession] = useState<AuthSession | null>(() => auth.restore()); return <Routes><Route path="/" element={session ? <Navigate to={session.role === 'hr' ? '/hr' : `/me/${session.employee_id}`} /> : <Login onLogin={setSession} />} /><Route path="/me/:id" element={session?.role === 'employee' ? <EmployeePage onSignOut={() => { auth.set(null); setSession(null) }} /> : <Navigate to="/" />} /><Route path="/hr" element={session?.role === 'hr' ? <HrPlaceholder /> : <Navigate to="/" />} /><Route path="*" element={<Navigate to="/" />} /></Routes> }
